---
- name: restart postgres
  service:
    name: "{{pg_service_name}}"
    state: restarted
    become: true

- name: enable automatic start
  systemd:
    name: "{{pg_service_name}}"
    enabled: yes
    state: started