---
- name: Install the repository RPM
  shell: >
    dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  become: yes

- name: Disable builtin postgresql module
  shell: >
    dnf -qy module disable postgresql
  become: yes

- name: Install require python package
  package:
    name:
      - python3-pycurl
      - python3-libselinux
      - python3-psycopg2
    state: present
  become: yes

- name: Install PostgreSQL {{pg_version}}
  package:
    name:
      - glibc-common
      - ca-certificates
      - postgresql{{ pg_version }}
      - postgresql{{ pg_version }}-server
      - postgresql{{ pg_version }}-contrib
      - sslutils_{{ pg_version }}
    state: present
    update_cache: yes
  become: true
  notify: enable automatic start

- name: Initialize the database
  shell: >
    /usr/pgsql-14/bin/postgresql-14-setup initdb
  become: yes
  ignore_errors: yes

# ToDo почему то не работает через модуль хз =(
- name: Enable automatic start
  shell: >
    systemctl enable postgresql-14
  become: yes
  ignore_errors: yes

- name: "Create a new database {{ db_name }}"
  postgresql_db:
    name: "{{ db_name }}"
    state: present
  become: yes
  become_user: postgres

- name: "Create a new user {{ db_user }}"
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: yes
  become_user: postgres

- name: "Grant {{ db_user }} access to the {{ db_name }}"
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: no
    privs: all
  become: yes
  become_user: postgres

- name: "Allow connection"
  postgresql_pg_hba:
    dest: "{{ pg_conf_path }}"
    contype: host
    databases: all
    method: md5
    users: harry
    create: true
  become: yes
  become_user: postgres
  notify: restart postgres