---
- name: Stop the PG service if it's running
  systemd:
    name: postgresql-14
    state: stopped
  become: yes
  ignore_errors: yes

- name: Remove require python package
  package:
    name:
      - python3-pycurl
      - python3-libselinux
      - python3-psycopg2
    state: absent
  become: yes

- name: Remove Postgres
  package:
    name:
      - postgresql14
      - postgresql14-server
      - postgresql14-contrib
      - sslutils_14
    state: absent
  become: yes