---
- name: Install Java
  package:
    name: java-11-openjdk-devel.x86_64
    state: latest
  become: yes

- name: Create group {{ tomcat_group }}
  group:
    name: "{{ tomcat_group }}"
    gid: "{{ tomcat_group_gid | default(omit) }}"
    state: present
  become: yes

- name: Create user {{ tomcat_user }}
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    # uid: "{{ tomcat_user_uid | default(omit) }}"
    state: present
  become: yes

- name: Create temp directory
  file:
    path: '{{ tomcat_temp_download_path }}'
    state: directory

- name: Download apache-tomcat-{{ tomcat_version }}
  get_url:
    url: "{{ tomcat_downloadURL }}/tomcat/tomcat-{{ tomcat_version.split('.')[0] }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: '{{ tomcat_temp_download_path }}'
    timeout: 180

- name: Unarchive apache-tomcat-{{ tomcat_version }}.tar.gz at {{ tomcat_install_path }}
  unarchive:
    src: "{{ tomcat_temp_download_path }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_path }}"
    remote_src: True
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    creates: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
  register: tomcat_installed
  become: yes

- name: Clean up temporary files
  file:
    path: '{{ tomcat_temp_download_path }}'
    state: absent
  changed_when: False
  become: yes